version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: euler-backend
    ports:
      - "3001:3001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./Backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: euler-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_SERVER_URL=http://localhost:3001/api/chat
      - VITE_START_URL=http://localhost:3001/api/start
      - VITE_FACEBOOK_LINK=https://www.facebook.com/le.hoang.nhi.404070
      - VITE_EMAIL=lhnhi420@gmail.com
      - VITE_API_GITHUB_PROFILE=https://api.github.com/users/lhnhidev
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
